# Generated by Django 5.1.6 on 2025-02-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prs_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.AddField(
            model_name="module",
            name="title",
            field=models.CharField(default="Module Title", max_length=50),
        ),
        migrations.AddField(
            model_name="professor",
            name="first_name",
            field=models.CharField(default="First Name", max_length=50),
        ),
        migrations.AddField(
            model_name="professor",
            name="last_name",
            field=models.CharField(default="Last Name", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="First Name", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="Last Name", max_length=50),
        ),
    ]
