# Generated by Django 5.1.6 on 2025-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prs_app", "0004_remove_student_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="modules",
            field=models.ManyToManyField(to="prs_app.moduleinstance"),
        ),
    ]
