# Generated by Django 5.1.6 on 2025-02-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prs_app", "0005_student_modules"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(default="email@host.domain", max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default="Password", max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(default="Last Name", max_length=50),
        ),
    ]
