# Generated by Django 5.1.6 on 2025-03-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prs_app", "0006_student_email_student_password_student_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rating",
            name="instance_id",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="professor_id",
        ),
        migrations.RemoveField(
            model_name="rating",
            name="student_id",
        ),
        migrations.AddField(
            model_name="rating",
            name="module_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prs_app.moduleinstance",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prs_app.professor",
            ),
        ),
        migrations.AddField(
            model_name="rating",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="prs_app.student",
            ),
        ),
    ]
