# Generated by Django 5.1.6 on 2025-03-01 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prs_app",
            "0007_remove_rating_instance_id_remove_rating_professor_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleinstance",
            name="instance_id",
        ),
        migrations.RemoveField(
            model_name="moduleinstance",
            name="module_code",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="professor_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.RemoveField(
            model_name="student",
            name="username",
        ),
        migrations.AddField(
            model_name="moduleinstance",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="prs_app.module",
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=models.TextField(default="Description"),
        ),
        migrations.AlterField(
            model_name="module",
            name="module_code",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="module",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="moduleinstance",
            name="professors",
            field=models.ManyToManyField(
                related_name="module_instances", to="prs_app.professor"
            ),
        ),
        migrations.AlterField(
            model_name="moduleinstance",
            name="semester",
            field=models.IntegerField(choices=[(1, "Spring"), (2, "Fall")]),
        ),
        migrations.AlterField(
            model_name="moduleinstance",
            name="year",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="professor",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="professor",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="professor",
            name="modules",
            field=models.ManyToManyField(
                related_name="professors", to="prs_app.module"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="module_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prs_app.moduleinstance"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prs_app.professor"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="prs_app.student"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="modules",
            field=models.ManyToManyField(
                related_name="students", to="prs_app.moduleinstance"
            ),
        ),
    ]
