# Generated by Django 5.1.6 on 2025-03-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prs_app", "0008_remove_moduleinstance_instance_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="username",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
