# Generated by Django 5.1.6 on 2025-03-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prs_app", "0009_student_password_student_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name",
        ),
    ]
