# Generated by Django 5.1.6 on 2025-03-02 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prs_app", "0010_remove_student_first_name_remove_student_last_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="email",
        ),
        migrations.RemoveField(
            model_name="student",
            name="password",
        ),
        migrations.RemoveField(
            model_name="student",
            name="username",
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
