# Generated by Django 5.1.6 on 2025-03-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("prs_app", "0015_alter_professor_professor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="modules",
        ),
    ]
