# Generated by Django 5.1.6 on 2025-03-02 14:19

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prs_app", "0016_remove_professor_modules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moduleinstance",
            name="year",
        ),
        migrations.AddField(
            model_name="moduleinstance",
            name="start_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(1900, 1, 1)),
                    django.core.validators.MaxValueValidator(datetime.date(2025, 3, 2)),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="moduleinstance",
            name="semester",
            field=models.IntegerField(choices=[(1, "First"), (2, "Second")]),
        ),
    ]
